### ISSUE TITLE
Django 1.8 migrate fails when using SplitField

### ISSUE THREAD

**Issue by approxit** [carljm/django-model-utils#169]
Say hello to #156 again in Django 1.8. Both `model_utils` versions from pip `2.2` and master `2.3a1`. Looks like `deconstruct()` does not help. Using `manage.py makemigrations` works fine. Error shows up using `manage.py migrate`. Both altering and adding `SplitField` fails.

    # part of migration file
    operations = [
        migrations.AddField(
            model_name='news',
            name='_content_excerpt',
            field=models.TextField(default='dupa', editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='content',
            field=model_utils.fields.SplitField(verbose_name='content'),
        ),
    ]

    # manage.py migrate
    Traceback (most recent call last):
      File "manage.py", line 9, in <module>
        execute_from_command_line(sys.argv)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
        utility.execute()
      File "/vagrant_env/local/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
        self.fetch_command(subcommand).run_from_argv(self.argv)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
        self.execute(*args, **cmd_options)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
        output = self.handle(*args, **options)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/core/management/commands/migrate.py", line 221, in handle
        executor.migrate(targets, plan, fake=fake, fake_initial=fake_initial)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 110, in migrate
        self.apply_migration(states[migration], migration, fake=fake, fake_initial=fake_initial)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/migrations/executor.py", line 147, in apply_migration
        state = migration.apply(state, schema_editor)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/migrations/migration.py", line 115, in apply
        operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/migrations/operations/fields.py", line 201, in database_forwards
        schema_editor.alter_field(from_model, from_field, to_field)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 489, in alter_field
        old_db_params, new_db_params, strict)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 200, in _alter_field
        self._remake_table(model, alter_fields=[(old_field, new_field)])
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/schema.py", line 137, in _remake_table
        self.create_model(temp_model)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 286, in create_model
        self.execute(sql, params or None)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/base/schema.py", line 111, in execute
        cursor.execute(sql, params)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 79, in execute
        return super(CursorDebugWrapper, self).execute(sql, params)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 64, in execute
        return self.cursor.execute(sql, params)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/utils.py", line 97, in __exit__
        six.reraise(dj_exc_type, dj_exc_value, traceback)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/utils.py", line 62, in execute
        return self.cursor.execute(sql)
      File "/vagrant_env/local/lib/python2.7/site-packages/django/db/backends/sqlite3/base.py", line 316, in execute
        return Database.Cursor.execute(self, query)
    django.db.utils.OperationalError: duplicate column name: _content_excerpt

**Comment by carljm** [comment]
That's odd. I haven't made use of `SplitField` in a long time, and likely won't have time to dig in and debug this soon. If you figure out what fix is needed, I'd be happy to review and merge a PR!

**Comment by pacahon** [comment]
The same situation with sqlite3
Found 2 problems:
* https://github.com/carljm/django-model-utils/blob/master/model_utils/fields.py#L234 -my PR  to fix it https://github.com/carljm/django-model-utils/pull/171
* `makemigrations` generate 2 migrations (that's annoying, don't know why it's happening)

In my case:
```
# Model field
text = SplitField(_("News|text"), help_text="help_text")
```

```
# First migration 
migrations.CreateModel(
...
    fields=[
    ('text', model_utils.fields.SplitField(help_text='help_text', no_excerpt_field=False, verbose_name='News|text')),
                    ('_text_excerpt', models.TextField(editable=False)),
    ]
    ...
)

# Second migration
migrations.AlterField(
    model_name='news',
    name='text',
    field=model_utils.fields.SplitField(help_text='help_text', no_excerpt_field=True, verbose_name='News|text'),
),
```
My solution:
* Describe excerpt field explicitly:
```
# In models.py
text = SplitField(_("News|text"), help_text="help_text", no_excerpt_field=True)
_text_excerpt = models.TextField(editable=False)
```
* Delete buggy migrations and create them again

**Comment by carljm** [comment]
I would guess the double migrations issue would be fixed by simply hardcoding `no_excerpt_field=True` in deconstruct output. I don't think adding the excerpt field explicitly to the model should be necessary (or make any difference).

**Comment by pacahon** [comment]
Have no idea how migrations using deconstruct() but I'll try your idea tomorrow with my code.
