### ISSUE TITLE
Missing runtests module in pypi package (2.5.1)

### ISSUE THREAD

**Issue by Germano0** [carljm/django-model-utils#230]
Hi, I am packaging python-django-model-utils to include it into Fedora repositories. While making the RPM package I obtained the error message `ImportError: No module named runtests`. I have asked in Fedora Python mailing list and I have been told that I get this message because the Pypi package does not include runtests module

```
$ rpmbuild -ba rpmbuild/SPECS/python-django-model-utils.spec 
Esecuzione(%prep) in corso: /bin/sh -e /var/tmp/rpm-tmp.L1zTGp
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ cd /home/user/rpmbuild/BUILD
+ rm -rf django-model-utils-2.5.1
+ /usr/bin/gzip -dc /home/user/rpmbuild/SOURCES/django-model-utils-2.5.1.tar.gz
+ /usr/bin/tar -xof -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd django-model-utils-2.5.1
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ exit 0
Esecuzione(%build) in corso: /bin/sh -e /var/tmp/rpm-tmp.n7VvPw
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ cd django-model-utils-2.5.1
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ /usr/bin/python2 setup.py build '--executable=/usr/bin/python2 -s'
running build
running build_py
creating build
creating build/lib
creating build/lib/model_utils
copying model_utils/models.py -> build/lib/model_utils
copying model_utils/choices.py -> build/lib/model_utils
copying model_utils/tracker.py -> build/lib/model_utils
copying model_utils/managers.py -> build/lib/model_utils
copying model_utils/__init__.py -> build/lib/model_utils
copying model_utils/fields.py -> build/lib/model_utils
creating build/lib/model_utils/tests
copying model_utils/tests/models.py -> build/lib/model_utils/tests
copying model_utils/tests/__init__.py -> build/lib/model_utils/tests
copying model_utils/tests/tests.py -> build/lib/model_utils/tests
copying model_utils/tests/fields.py -> build/lib/model_utils/tests
creating build/lib/model_utils/locale
creating build/lib/model_utils/locale/de
creating build/lib/model_utils/locale/de/LC_MESSAGES
copying model_utils/locale/de/LC_MESSAGES/django.po -> build/lib/model_utils/locale/de/LC_MESSAGES
copying model_utils/locale/de/LC_MESSAGES/django.mo -> build/lib/model_utils/locale/de/LC_MESSAGES
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ /usr/bin/python3 setup.py build '--executable=/usr/bin/python3 -s'
running build
running build_py
+ exit 0
Esecuzione(%install) in corso: /bin/sh -e /var/tmp/rpm-tmp.enmS4W
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ '[' /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64 '!=' / ']'
+ rm -rf /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64
++ dirname /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64
+ mkdir -p /home/user/rpmbuild/BUILDROOT
+ mkdir /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64
+ cd django-model-utils-2.5.1
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ /usr/bin/python2 setup.py install -O1 --skip-build --root /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64
running install
running install_lib
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
copying build/lib/model_utils/models.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
copying build/lib/model_utils/choices.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
copying build/lib/model_utils/tracker.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
copying build/lib/model_utils/managers.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
copying build/lib/model_utils/__init__.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/locale
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/locale/de
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/locale/de/LC_MESSAGES
copying build/lib/model_utils/locale/de/LC_MESSAGES/django.po -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/locale/de/LC_MESSAGES
copying build/lib/model_utils/locale/de/LC_MESSAGES/django.mo -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/locale/de/LC_MESSAGES
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests
copying build/lib/model_utils/tests/models.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests
copying build/lib/model_utils/tests/__init__.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests
copying build/lib/model_utils/tests/tests.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests
copying build/lib/model_utils/tests/fields.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests
copying build/lib/model_utils/fields.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/models.py to models.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/choices.py to choices.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tracker.py to tracker.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/managers.py to managers.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/__init__.py to __init__.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests/models.py to models.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests/__init__.py to __init__.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests/tests.py to tests.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/tests/fields.py to fields.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/model_utils/fields.py to fields.pyc
writing byte-compilation script '/tmp/tmpFmsEDR.py'
/usr/bin/python2 -O /tmp/tmpFmsEDR.py
removing /tmp/tmpFmsEDR.py
running install_egg_info
running egg_info
writing requirements to django_model_utils.egg-info/requires.txt
writing django_model_utils.egg-info/PKG-INFO
writing top-level names to django_model_utils.egg-info/top_level.txt
writing dependency_links to django_model_utils.egg-info/dependency_links.txt
reading manifest file 'django_model_utils.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'TODO.rst'
warning: no files found matching 'django.po' under directory 'locale'
writing manifest file 'django_model_utils.egg-info/SOURCES.txt'
Copying django_model_utils.egg-info to /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7/site-packages/django_model_utils-2.5.1-py2.7.egg-info
running install_scripts
+ CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic'
+ /usr/bin/python3 setup.py install -O1 --skip-build --root /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64
running install
running install_lib
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
copying build/lib/model_utils/models.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
copying build/lib/model_utils/choices.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
copying build/lib/model_utils/tracker.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
copying build/lib/model_utils/managers.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
copying build/lib/model_utils/__init__.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/locale
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/locale/de
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/locale/de/LC_MESSAGES
copying build/lib/model_utils/locale/de/LC_MESSAGES/django.po -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/locale/de/LC_MESSAGES
copying build/lib/model_utils/locale/de/LC_MESSAGES/django.mo -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/locale/de/LC_MESSAGES
creating /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests
copying build/lib/model_utils/tests/models.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests
copying build/lib/model_utils/tests/__init__.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests
copying build/lib/model_utils/tests/tests.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests
copying build/lib/model_utils/tests/fields.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests
copying build/lib/model_utils/fields.py -> /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/models.py to models.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/choices.py to choices.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tracker.py to tracker.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/managers.py to managers.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests/models.py to models.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests/__init__.py to __init__.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests/tests.py to tests.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/tests/fields.py to fields.cpython-35.pyc
byte-compiling /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/model_utils/fields.py to fields.cpython-35.pyc
writing byte-compilation script '/tmp/tmpiywcsixh.py'
/usr/bin/python3 -O /tmp/tmpiywcsixh.py
removing /tmp/tmpiywcsixh.py
running install_egg_info
running egg_info
writing django_model_utils.egg-info/PKG-INFO
writing top-level names to django_model_utils.egg-info/top_level.txt
writing requirements to django_model_utils.egg-info/requires.txt
writing dependency_links to django_model_utils.egg-info/dependency_links.txt
reading manifest file 'django_model_utils.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'TODO.rst'
warning: no files found matching 'django.po' under directory 'locale'
writing manifest file 'django_model_utils.egg-info/SOURCES.txt'
Copying django_model_utils.egg-info to /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5/site-packages/django_model_utils-2.5.1-py3.5.egg-info
running install_scripts
+ /usr/lib/rpm/find-debuginfo.sh --strict-build-id -m --run-dwz --dwz-low-mem-die-limit 10000000 --dwz-max-die-limit 110000000 /home/user/rpmbuild/BUILD/django-model-utils-2.5.1
/usr/lib/rpm/sepdebugcrcfix: Updated 0 CRC32s, 0 CRC32s did match.
find: 'debug': No such file or directory
+ '[' noarch = noarch ']'
+ case "${QA_CHECK_RPATHS:-}" in
+ /usr/lib/rpm/check-buildroot
+ /usr/lib/rpm/brp-compress
+ /usr/lib/rpm/brp-strip-static-archive /usr/bin/strip
+ /usr/lib/rpm/brp-python-bytecompile /usr/bin/python 1
Bytecompiling .py files below /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python2.7 using /usr/bin/python2.7
Bytecompiling .py files below /home/user/rpmbuild/BUILDROOT/python-django-model-utils-2.5.1-1.fc24.x86_64/usr/lib/python3.5 using /usr/bin/python3.5
+ /usr/lib/rpm/brp-python-hardlink
+ /usr/lib/rpm/redhat/brp-java-repack-jars
Esecuzione(%check) in corso: /bin/sh -e /var/tmp/rpm-tmp.O6olzz
+ umask 022
+ cd /home/user/rpmbuild/BUILD
+ cd django-model-utils-2.5.1
+ /usr/bin/python2 setup.py test
running test
running egg_info
writing requirements to django_model_utils.egg-info/requires.txt
writing django_model_utils.egg-info/PKG-INFO
writing top-level names to django_model_utils.egg-info/top_level.txt
writing dependency_links to django_model_utils.egg-info/dependency_links.txt
reading manifest file 'django_model_utils.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching 'TODO.rst'
warning: no files found matching 'django.po' under directory 'locale'
writing manifest file 'django_model_utils.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 54, in <module>
    'locale/*/LC_MESSAGES/django.po','locale/*/LC_MESSAGES/django.mo'
  File "/usr/lib64/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib64/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/usr/lib/python2.7/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/usr/lib64/python2.7/unittest/main.py", line 94, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python2.7/unittest/main.py", line 149, in parseArgs
    self.createTests()
  File "/usr/lib64/python2.7/unittest/main.py", line 158, in createTests
    self.module)
  File "/usr/lib64/python2.7/unittest/loader.py", line 130, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/usr/lib64/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named runtests
errore: Stato d'uscita errato da /var/tmp/rpm-tmp.O6olzz (%check)


Errori di compilazione RPM:
    Stato d'uscita errato da /var/tmp/rpm-tmp.O6olzz (%check)
```

**Comment by carljm** [comment]
Released 2.5.2 with `runtests.py` included in the sdist. Thanks for packaging!
